### ISSUE TITLE
Error getting data repo status: fatal: Not a git repository

### ISSUE THREAD

**Issue by sosiouxme** [openshift/doozer#28]
In my doozer config I set:

`data_path: https://github.com/openshift/ocp-build-data/`  <-- with trailing slash

This causes a confusing error:
```
Error getting data repo status: fatal: Not a git repository (or any of the parent directories): .git
```

It works if I remove the trailing `/`

**Comment by vfreex** [comment]
This is because pygitdata uses `sys.path.basename` to extract the directory name of the git repository. `https://github.com/openshift/ocp-build-data/` gets an empty string.

**Comment by tbielawa** [comment]
Moved to jira. https://issues.redhat.com/browse/ART-1515
