### ISSUE TITLE
missing doozerlib after update

### ISSUE THREAD

**Issue by jeffdyoung** [openshift/doozer#50]
I updated doozer on my ppc64le build machine (rhel7), and it seems i'm missing a library:

```
[jeyoung@b ~]$ doozer version
Traceback (most recent call last):
  File "/bin/doozer", line 6, in <module>
    from doozerlib import state
ImportError: cannot import name state
```

**Comment by adammhaile** [comment]
How did you update it? state is new so it sounds like it updated the main
doozer cli file but didn't pull the latest doozerlib.
pip is super weird sometimes... my suggestion is to uninstall and reinstall

**Comment by jeffdyoung** [comment]
From my user account:

`[jeyoung@b ~]$ sudo pip install -U rh-doozer`

uninstalling/reinstall has not worked either.

I do see doozerlib here:
```
[jeyoung@b ~]$ sudo find / -name doozerlib*
/root/.local/lib/python2.7/site-packages/doozerlib
/home/jeyoung/.local/lib/python2.7/site-packages/-oozerlib/doozerlib
```

**Comment by adammhaile** [comment]
**`-oozerlib`** ??? That seems suspect.
For one, I highly recommend running it in a virtual env. That may help a lot.
Particularly it's suspect to me that you have doozerlib found in 2 different site-packages. Can you send an `ls -al` of each of those directories?
With it installed what is the output of `pip list | grep doozer` ? Also, `pip freeze | grep doozer`

**Comment by jeffdyoung** [comment]
figured it out. 
Because the install script didn't exist when i setup this machine, I had initially installed as root (or maybe with sudo as my user?) I was getting permission issues in these directories when I tried to upgrade:
/usr/lib/python2.7/
/usr/bin

Once I fixed the permissions all was well here:
`pip install -U rh-doozer --user `
 
Thanks!
