### ISSUE TITLE
OS_GIT_MAJOR: unbound variable error on local OCP builds

### ISSUE THREAD

**Issue by jeffdyoung** [openshift/doozer#67]
I'm seeing this error on any container built out of global_ose:

```
2019-03-26 14:32:47,546 ERROR [containers/openshift-enterprise-cli] Error running imagebuilder -mount : out=--> FROM openshift/golang-builder:1.10 as builder
--> WORKDIR /go/src/github.com/openshift/origin
--> COPY . .
--> RUN make build WHAT=cmd/oc
hack/build-go.sh cmd/oc 
/go/src/github.com/openshift/origin/hack/lib/constants.sh: line 110: OS_GIT_MAJOR: unbound variable
[ERROR] hack/lib/constants.sh:110: `ldflags+=($(os::build::ldflag "${OS_GO_PACKAGE}/pkg/version.majorFromGit" "${OS_GIT_MAJOR}"))` exited with status 1.
[ERROR] hack/lib/build/binaries.sh:172: `version_ldflags=$(os::build::ldflags)` exited with status 1.
[ERROR] hack/lib/build/binaries.sh:150: `local -a binaries=("$@")` exited with status 1.
[ERROR] hack/build-go.sh exited with code 1 after 00h 00m 02s
make: *** [build] Error 1
running 'make build WHAT=cmd/oc' failed with exit code 2
```

OS: fedora 29 and rhel7
Arch: x86_64
Doozer: v0.4.4

Steps to reproduce:
- clean working directory
- settings = 
```
#Global option overrides that can only be set from settings.yaml
global_opts:
  rhpkg_push_timeout:
  distgit_threads:
  rhpkg_clone_timeout:

#Persistent working directory to use
working_dir: /home/jeyoung/doozerdata

#Git URL or File Path to build data
data_path:  https://github.com/openshift/ocp-build-data

#Sub-group directory or branch to pull build data
group: openshift-4.0 #(or openshift4.1)

#Username for running rhpkg / brew / tito
user: jeyoung
```
- doozer --local --latest-parent-version -i openshift-enterprise-cli images:rebase
- doozer --local --latest-parent-version -i openshift-enterprise-cli images:build

**Comment by jeffdyoung** [comment]
ATM I can work around by adding this to the Dockerfile:
```
RUN KUBE_GIT_VERSION=0 KUBE_GIT_MINOR=0 KUBE_GIT_MAJOR=0 OS_GIT_COMMIT=0 OS_GIT_VERSION=0 OS_GIT_MAJOR=0 OS_GIT_MINOR=0 make build WHAT=cmd/oc;
```

**Comment by adammhaile** [comment]
@sosiouxme any thoughts here? Sounds like OS_GIT_MAJOR is something that's maybe being set by OSBS? Only thing I can think of since this works in regular builds.

**Comment by sosiouxme** [comment]
It's not an OSBS thing. It's an `ose hack/lib` thing. I think this might genuinely be a difference in the arches somehow, and we just haven't seen it before because we weren't doing any of this in container builds before v4. I have seen something like this before and will be happy to look at it soon, I know it's a blocker for you @jeffdyoung but I have some other pressing priorities.

**Comment by jeffdyoung** [comment]
Not a blocker @sosiouxme  :) 
ATM, I'm just making sure things can build on other archs, and I can workaround by adding the variables to the Dockerfiles. 

I don't think its an arch issue,  I can duplicate on local builds w/x86.

**Comment by thiagoalessio** [comment]
Hi @jeffdyoung doozer changed so much since March, we are already in version https://pypi.org/project/rh-doozer/0.5.26/
i'll close this for now, but **please** feel free to re-open if it is still unresolved.
