### ISSUE TITLE
License on pypy is INTERNAL

### ISSUE THREAD

**Issue by iranzo** [openshift/doozer#99]
On https://github.com/openshift/doozer/blob/master/setup.py#L24 we say that license is internal, but then we publish the code... shouldn't it be adapted and add a proper LICENSE file to this repo?

Thanks

**Comment by adammhaile** [comment]
Good catch. I'll update that soon... this used to be purely internal and that just never got updated.

**Comment by iranzo** [comment]
Thanks Adam, it will be also good to add a LICENSE file to the repo :-)
